export interface ColorTokens {
  primary: string;
  primaryDark: string;
  primaryLight: string;
  primaryMuted: string;
  background: string;
  backgroundSoft: string;
  surface: string;
  surfaceSecondary: string;
  surfaceTertiary: string;
  surfaceHover: string;
  border: string;
  borderLight: string;
  borderStrong: string;
  divider: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  textMuted: string;
  textDark: string;
  textOnPrimary: string;
  success: string;
  successTint: string;
  error: string;
  errorLight: string;
  errorTint: string;
  warning: string;
  warningTint: string;
  danger: string;
  dangerDark: string;
  nivelPrimaria: string;
  nivelSecundaria: string;
  nivelPreparatoria: string;
  nivelUniversidad: string;
  purple: string;
  teal: string;
  tealLight: string;
  indigo: string;
  amber: string;
  metricBlue: string;
  metricTeal: string;
  metricAmber: string;
  metricRed: string;
  bannerBg: string;
  bannerAccent: string;
  toggleActive: string;
  progressTrack: string;
  skeleton: string;
  overlay: string;
  primaryTint: string;
  successLight: string;
  purpleTint: string;

  // Stitch Material 3 surface system
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  onSurface: string;
  onSurfaceVariant: string;
  outlineVariant: string;
  primaryContainer: string;
  secondaryContainer: string;
  errorContainer: string;
  inverseSurface: string;
  shadowBlue: string;
  shadowBlueLift: string;
}

export type ThemeMode = "light" | "dark";
export type FontSizeMode = "small" | "medium" | "large" | "xlarge";
export type DaltonismoMode = "none" | "protanopia" | "deuteranopia" | "tritanopia";
