import { StyleSheet } from "react-native";
import { COLORS } from "../../../../types";

// Estilos compartidos por la pantalla de importacion y sus etapas.
// Se centralizan aqui para mantener una sola fuente de verdad al dividir
// la pantalla en componentes por etapa (idle, processing, preview, success, error).
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  safeArea: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 110 },
  headerRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
  headerIconButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  headerTitle: { color: COLORS.primary, fontSize: 30, fontWeight: "800" },
  pageTitle: { color: COLORS.text, fontSize: 48, fontWeight: "800", marginBottom: 6 },
  pageSubtitle: { color: COLORS.textSecondary, fontSize: 30, lineHeight: 40, marginBottom: 12 },
  card: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    padding: 16,
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  heroIconWrap: {
    width: 96,
    height: 96,
    borderRadius: 999,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitle: { color: COLORS.text, fontSize: 34, fontWeight: "800", textAlign: "center" },
  cardText: { color: COLORS.textSecondary, fontSize: 25, textAlign: "center", lineHeight: 34 },
  primaryButton: {
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    width: "100%",
  },
  primaryButtonText: { color: COLORS.surface, fontSize: 22, fontWeight: "800" },
  linkButton: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 4 },
  linkButtonText: { color: COLORS.primary, fontSize: 20, fontWeight: "700" },
  progressTrack: {
    width: "100%",
    height: 8,
    borderRadius: 999,
    backgroundColor: COLORS.border,
    overflow: "hidden",
  },
  progressFill: {
    width: "60%",
    height: "100%",
    borderRadius: 999,
    backgroundColor: COLORS.primary,
  },
  fileRow: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  fileIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COLORS.primaryTint,
    alignItems: "center",
    justifyContent: "center",
  },
  fileName: { color: COLORS.text, fontSize: 20, fontWeight: "700" },
  changeFileText: { color: COLORS.primary, fontSize: 18, fontWeight: "700" },
  previewTitle: { color: COLORS.text, fontSize: 38, fontWeight: "800", marginBottom: 8 },
  statsRow: { flexDirection: "row", gap: 8, marginBottom: 10 },
  validBadge: {
    backgroundColor: COLORS.successTint,
    borderWidth: 1,
    borderColor: COLORS.success,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  validText: { color: COLORS.success, fontSize: 16, fontWeight: "800" },
  invalidBadge: {
    backgroundColor: "#FFE8E8",
    borderWidth: 1,
    borderColor: "#F2C6C6",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  invalidText: { color: COLORS.dangerDark, fontSize: 16, fontWeight: "800" },
  tableCard: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 14,
    overflow: "hidden",
    marginBottom: 12,
  },
  tableHead: {
    flexDirection: "row",
    backgroundColor: COLORS.background,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  colHead: {
    color: COLORS.textSecondary,
    fontSize: 12,
    textTransform: "uppercase",
    fontWeight: "800",
  },
  tableRow: {
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.background,
    gap: 6,
  },
  errorRow: { backgroundColor: "#FFF3F3" },
  colValue: { color: COLORS.text, fontSize: 18, fontWeight: "600" },
  errorCellText: { color: COLORS.dangerDark, fontWeight: "700" },
  rowErrorDetail: { color: COLORS.dangerDark, fontSize: 14, marginTop: 2 },
  actionsCard: {
    backgroundColor: COLORS.primaryTint,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
  },
  actionsRow: { flexDirection: "row", gap: 10 },
  cancelButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: { color: COLORS.textSecondary, fontSize: 20, fontWeight: "800" },
  importButton: {
    flex: 1.6,
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  importButtonText: { color: COLORS.surface, fontSize: 20, fontWeight: "800" },
  successTitle: { color: COLORS.text, fontSize: 45, fontWeight: "800", textAlign: "center" },
  secondaryButton: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderStrong,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    width: "100%",
  },
  secondaryButtonText: { color: COLORS.textSecondary, fontSize: 20, fontWeight: "700" },
  errorTitle: { color: COLORS.text, fontSize: 45, fontWeight: "800", textAlign: "center" },
});
